import crafttweaker.item.IIngredient;


//Metal unification
/*
	METAL_TYPE: {
		block: ITEM_STACK,
		dust: ITEM_STACK,
		gear: ITEM_STACK,
		ingot: ITEM_STACK,
		liquid: <liquid:lava>,
		nugget: ITEM_STACK,
		plate: ITEM_STACK,
		rod: ITEM_STACK
	}
*/
global metalItems as IIngredient[string][string] = {
	aluminium: {
		block: <thermalfoundation:storage:4>,
		dust: <thermalfoundation:material:68>,
		gear: <thermalfoundation:material:260>,
		ingot: <thermalfoundation:material:132>,
		liquid: <liquid:aluminum>,
		nugget: <thermalfoundation:material:196>,
		plate: <thermalfoundation:material:324>,
		rod: <immersiveengineering:material:3>
	},
	boron: {
		block: <nuclearcraft:ingot_block:5>,
		dust: <nuclearcraft:dust:5>,
		gear: null,
		ingot: <nuclearcraft:ingot:5>,
		liquid: <nuclearcraft:fluid_boron>,
		nugget: null,
		plate: null,
		rod: null
	},
	brass: {
		block: <techreborn:storage:5>,
		dust: <techreborn:dust:6>,
		gear: <railcraft:gear>,
		ingot: <techreborn:ingot:1>,
		liquid: null,
		nugget: <techreborn:nuggets:1>,
		plate: <techreborn:plates:17>,
		rod: null
	},
	bronze: {
		block: <thermalfoundation:storage_alloy:3>,
		dust: <thermalfoundation:material:99>,
		gear: <thermalfoundation:material:291>,
		ingot: <thermalfoundation:material:163>,
		liquid: <liquid:bronze>,
		nugget: <thermalfoundation:material:227>,
		plate: <thermalfoundation:material:355>,
		rod: null
	},
	chrome: {
		block: <techreborn:storage:3>,
		dust: <techreborn:dust:10>,
		gear: null,
		ingot: <techreborn:ingot:3>,
		liquid: null,
		nugget: <techreborn:nuggets:3>,
		plate: <techreborn:plates:19>,
		rod: null
	},
	compressedIron: {
		block: <enderio:block_alloy:4>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:4>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:4>,
		plate: null,
		rod: null
	},
	conductiveIron: {
		block: <pneumaticcraft:compressed_iron_block>,
		dust: null,
		gear: <pneumaticcraft:compressed_iron_gear>,
		ingot: <pneumaticcraft:ingot_iron_compressed>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	constantan: {
		block: <thermalfoundation:storage_alloy:4>,
		dust: <thermalfoundation:material:100>,
		gear: <thermalfoundation:material:292>,
		ingot: <thermalfoundation:material:164>,
		liquid: null,
		nugget: <thermalfoundation:material:228>,
		plate: <thermalfoundation:material:356>,
		rod: null
	},
	copper: {
		block: <thermalfoundation:storage>,
		clump: <mekanism:clump:3>,
		crystal: <mekanism:crystal:3>,
		dirtyDust: <mekanism:dirtydust:3>,
		dust: <thermalfoundation:material:64>,
		gear: <thermalfoundation:material:256>,
		ingot: <thermalfoundation:material:128>,
		liquid: <liquid:copper>,
		nugget: <thermalfoundation:material:192>,
		plate: <thermalfoundation:material:320>,
		rod: <immersiveposts:stick_copper>,
		shard: <mekanism:shard:3>
	},
	darkSteel: {
		block: <enderio:block_alloy:6>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:6>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:6>,
		plate: null,
		rod: null,
	},
	ebonyPsiMetal: {
		block: <psi:psi_decorative:7>,
		dust: null,
		gear: null,
		ingot: <psi:material:3>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	electricalSteel: {
		block: <enderio:block_alloy>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget>,
		plate: null,
		rod: null,
	},
	electrum: {
		block: <thermalfoundation:storage_alloy:1>,
		dust: <thermalfoundation:material:97>,
		gear: <thermalfoundation:material:289>,
		ingot: <thermalfoundation:material:161>,
		liquid: <liquid:electrum>,
		nugget: <thermalfoundation:material:225>,
		plate: <thermalfoundation:material:353>,
		rod: null
	},
	elementium: {
		block: <botania:storage:2>,
		dust: null,
		gear: null,
		ingot: <botania:manaresource:7>,
		liquid: null,
		nugget: <botania:manaresource:19>,
		plate: null,
		rod: null
	},
	endSteel: {
		block: <enderio:block_alloy:8>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:8>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:8>,
		plate: null,
		rod: null,
	},
	enderium: {
		block: <thermalfoundation:storage_alloy:7>,
		dust: <thermalfoundation:material:103>,
		gear: <thermalfoundation:material:295>,
		ingot: <thermalfoundation:material:167>,
		liquid: null,
		nugget: <thermalfoundation:material:231>,
		plate: <thermalfoundation:material:359>,
		rod: null
	},
	energeticAlloy: {
		block: <enderio:block_alloy:1>,
		dust: <nuclearcraft:compound:2>,
		gear: null,
		ingot: <enderio:item_alloy_ingot:1>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:1>,
		plate: null,
		rod: null
	},
	enhancedGalgadorian: {
		block: <stevescarts:blockmetalstorage:2>,
		dust: null,
		gear: null,
		ingot: <stevescarts:modulecomponents:49>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	fluxedElectrum: {
		block: <redstonearsenal:storage>,
		dust: <redstonearsenal:material>,
		gear: <redstonearsenal:material:96>,
		ingot: <redstonearsenal:material:32>,
		liquid: null,
		nugget: <redstonearsenal:material:64>,
		plate: <redstonearsenal:material:128>,
		rod: null
	},
	galena: {
		block: null,
		dust: <techreborn:dust:23>,
		gear: null,
		ingot: null,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	galgadorian: {
		block: <stevescarts:blockmetalstorage:1>,
		dust: null,
		gear: null,
		ingot: <stevescarts:modulecomponents:47>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	gold: {
		block: <minecraft:gold_block>,
		clump: <mekanism:clump:1>,
		crystal: <mekanism:crystal:1>,
		dirtyDust: <mekanism:dirtydust:1>,
		dust: <thermalfoundation:material:1>,
		gear: <thermalfoundation:material:25>,
		ingot: <minecraft:gold_ingot>,
		liquid: <liquid:gold>,
		nugget: <minecraft:gold_nugget>,
		plate: <thermalfoundation:material:33>,
		rod: null,
		shard: <mekanism:shard:1>
	},
	invar: {
		block: <thermalfoundation:storage_alloy:2>,
		dust: <thermalfoundation:material:98>,
		gear: <thermalfoundation:material:290>,
		ingot: <thermalfoundation:material:162>,
		liquid: null,
		nugget: <thermalfoundation:material:226>,
		plate: <thermalfoundation:material:354>,
		rod: null
	},
	iridium: {
		block: <thermalfoundation:storage:7>,
		dust: <thermalfoundation:material:71>,
		gear: <thermalfoundation:material:263>,
		ingot: <thermalfoundation:material:135>,
		liquid: null,
		nugget: <thermalfoundation:material:199>,
		plate: <thermalfoundation:material:327>,
		rod: null
	},
	iron: {
		block: <minecraft:iron_block>,
		clump: <mekanism:clump>,
		crystal: <mekanism:crystal>,
		dirtyDust: <mekanism:dirtydust>,
		dust: <thermalfoundation:material>,
		gear: <thermalfoundation:material:24>,
		ingot: <minecraft:iron_ingot>,
		liquid: <liquid:iron>,
		nugget: <minecraft:iron_nugget>,
		plate: <thermalfoundation:material:32>,
		rod: <immersiveengineering:material:1>,
		shard: <mekanism:shard>
	},
	ironAlloy: {
		block: <enderio:block_alloy:9>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:9>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:9>,
		plate: null,
		rod: null,
	},
	ivoryPsiMetal: {
		block: <psi:psi_decorative:8>,
		dust: null,
		gear: null,
		ingot: <psi:material:4>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	lead: {
		block: <thermalfoundation:storage:3>,
		clump: <mekanism:clump:6>,
		crystal: <mekanism:crystal:6>,
		dirtyDust: <mekanism:dirtydust:6>,
		dust: <thermalfoundation:material:67>,
		gear: <thermalfoundation:material:259>,
		ingot: <thermalfoundation:material:131>,
		liquid: <liquid:lead>,
		nugget: <thermalfoundation:material:195>,
		plate: <thermalfoundation:material:323>,
		rod: null,
		shard: <mekanism:shard:6>
	},
	lithium: {
		block: <nuclearcraft:ingot_block:6>,
		dust: <nuclearcraft:dust:6>,
		gear: null,
		ingot: <nuclearcraft:ingot:6>,
		liquid: <nuclearcraft:fluid_lithium>,
		nugget: null,
		plate: null,
		rod: null
	},
	lumium: {
		block: <thermalfoundation:storage_alloy:6>,
		dust: <thermalfoundation:material:102>,
		gear: <thermalfoundation:material:294>,
		ingot: <thermalfoundation:material:166>,
		liquid: null,
		nugget: <thermalfoundation:material:230>,
		plate: <thermalfoundation:material:358>,
		rod: null
	},
	magnesium: {
		block: <nuclearcraft:ingot_block:7>,
		dust: <nuclearcraft:dust:7>,
		gear: null,
		ingot: <nuclearcraft:ingot:7>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	manaInfused: {
		block: <thermalfoundation:storage:8>,
		dust: <thermalfoundation:material:72>,
		gear: <thermalfoundation:material:264>,
		ingot: <thermalfoundation:material:136>,
		liquid: null,
		nugget: <thermalfoundation:material:200>,
		plate: <thermalfoundation:material:328>,
		rod: null
	},
	manaSteel: {
		block: <botania:storage>,
		dust: null,
		gear: null,
		ingot: <botania:manaresource>,
		liquid: null,
		nugget: <botania:manaresource:17>,
		plate: null,
		rod: null
	},
	nickel: {
		block: <thermalfoundation:storage:5>,
		dust: <thermalfoundation:material:69>,
		gear: <thermalfoundation:material:261>,
		ingot: <thermalfoundation:material:133>,
		liquid: <liquid:nickel>,
		nugget: <thermalfoundation:material:197>,
		plate: <thermalfoundation:material:325>,
		rod: null
	},
	osmium: {
		block: <mekanism:basicblock>,
		clump: <mekanism:clump:2>,
		crystal: <mekanism:crystal:2>,
		dirtyDust: <mekanism:dirtydust:2>,
		dust: <mekanism:dust:2>,
		gear: null,
		ingot: <mekanism:ingot:1>,
		nugget: <mekanism:nugget:1>,
		plate: null,
		rod: null,
		shard: <mekanism:shard:2>
	},
	platinum: {
		block: <thermalfoundation:storage:6>,
		dust: <thermalfoundation:material:70>,
		gear: <thermalfoundation:material:262>,
		ingot: <thermalfoundation:material:134>,
		liquid: null,
		nugget: <thermalfoundation:material:198>,
		plate: <thermalfoundation:material:326>,
		rod: null
	},
	psiMetal: {
		block: <psi:psi_decorative:1>,
		dust: <psi:material>,
		gear: null,
		ingot: <psi:material:1>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	pulsatingIron: {
		block: <enderio:block_alloy:5>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:5>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:5>,
		plate: null,
		rod: null,
	},
	redstoneAlloy: {
		block: <enderio:block_alloy:3>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:3>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:3>,
		plate: null,
		rod: null,
	},
	reinforcedMetal: {
		block: <stevescarts:blockmetalstorage>,
		dust: null,
		gear: null,
		ingot: <stevescarts:modulecomponents:22>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null,
	},
	rutile: {
		block: <stevescarts:blockmetalstorage>,
		dust: null,
		gear: null,
		ingot: <stevescarts:modulecomponents:22>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null,
	},
	signalum: {
		block: <thermalfoundation:storage_alloy:5>,
		dust: <thermalfoundation:material:101>,
		gear: <thermalfoundation:material:293>,
		ingot: <thermalfoundation:material:165>,
		liquid: null,
		nugget: <thermalfoundation:material:229>,
		plate: <thermalfoundation:material:357>,
		rod: null
	},
	silver: {
		block: <thermalfoundation:storage:2>,
		clump: <mekanism:clump:5>,
		crystal: <mekanism:crystal:5>,
		dirtyDust: <mekanism:dirtydust:5>,
		dust: <thermalfoundation:material:66>,
		gear: <thermalfoundation:material:258>,
		ingot: <thermalfoundation:material:130>,
		liquid: <liquid:silver>,
		nugget: <thermalfoundation:material:194>,
		plate: <thermalfoundation:material:322>,
		rod: null,
		shard: <mekanism:shard:5>
	},
	soularium: {
		block: <enderio:block_alloy:7>,
		dust: null,
		gear: null,
		ingot: <enderio:item_alloy_ingot:7>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:7>,
		plate: null,
		rod: null
	},
	soulForgedSteel: {
		block: <betterwithmods:steel_block>,
		dust: null,
		gear: <betterwithmods:material:48>,
		ingot: <betterwithmods:material:14>,
		liquid: null,
		nugget: <betterwithmods:material:30>,
		plate: <betterwithmods:material:51>,
		rod: null
	},	
	starMetal: {
		block: null,
		dust: null,
		gear: null,
		ingot: <astralsorcery:itemcraftingcomponent:1>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},
	steel: {
		block: <thermalfoundation:storage_alloy>,
		dust: <thermalfoundation:material:96>,
		gear: <thermalfoundation:material:288>,
		ingot: <thermalfoundation:material:160>,
		liquid: null,
		nugget: <thermalfoundation:material:224>,
		plate: <thermalfoundation:material:352>,
		rod: <immersiveengineering:material:2>
	},
	terraSteel: {
		block: <botania:storage:1>,
		dust: null,
		gear: null,
		ingot: <botania:manaresource:4>,
		liquid: null,
		nugget: <botania:manaresource:18>,
		plate: null,
		rod: null
	},
	tin: {
		block: <thermalfoundation:storage:1>,
		clump: <mekanism:clump:4>,
		crystal: <mekanism:crystal:4>,
		dirtyDust: <mekanism:dirtydust:4>,
		dust: <thermalfoundation:material:65>,
		gear: <thermalfoundation:material:257>,
		ingot: <thermalfoundation:material:129>,
		liquid: <liquid:tin>,
		nugget: <thermalfoundation:material:193>,
		plate: <thermalfoundation:material:321>,
		rod: null,
		shard: <mekanism:shard:4>
	},
	titanium: {
		block: <techreborn:storage:2>,
		dust: <techreborn:dust:54>,
		gear: null,
		ingot: <techreborn:ingot:14>,
		liquid: null,
		nugget: <techreborn:nuggets:14>,
		plate: <techreborn:plates:30>,
		rod: null
	},
	thaumium: {
		block: <thaumcraft:metal_thaumium>,
		dust: null,
		gear: null,
		ingot: <thaumcraft:ingot>,
		liquid: null,
		nugget: <thaumcraft:nugget:6>,
		plate: <thaumcraft:plate:2>,
		rod: null
	},
	thorium: {
		block: <nuclearcraft:ingot_block:3>,
		dust: <nuclearcraft:dust:3>,
		gear: null,
		ingot: <nuclearcraft:ingot:3>,
		liquid: null,
		nugget: null,
		plate: null,
		rod: null
	},

	tungsten: {
		block: <techreborn:storage:10>,
		dust: <techreborn:dust:55>,
		gear: null,
		ingot: <techreborn:ingot:15>,
		liquid: null,
		nugget: <techreborn:nuggets:15>,
		plate: <techreborn:plates:31>,
		rod: null
	},
	tungstenSteel: {
		block: <techreborn:storage2>,
		dust: null,
		gear: null,
		ingot: <techreborn:ingot:17>,
		liquid: null,
		nugget: <techreborn:nuggets:17>,
		plate: <techreborn:plates:32>,
		rod: null
	},
	uranium: {
		block: <immersiveengineering:storage:5>,
		dust: <immersiveengineering:metal:14>,
		gear: null,
		ingot: <immersiveengineering:metal:5>,
		liquid: <liquid:uranium>,
		nugget: <immersiveengineering:metal:25>,
		plate: <immersiveengineering:metal:35>,
		rod: null
	},
	vibrantAlloy: {
		block: <enderio:block_alloy:2>,
		dust: null,
		gear: <enderio:item_material:13>,
		ingot: <enderio:item_alloy_ingot:2>,
		liquid: null,
		nugget: <enderio:item_alloy_nugget:2>,
		plate: null,
		rod: null
	},
	voidMetal: {
		block: <thaumcraft:metal_void>,
		dust: null,
		gear: null,
		ingot: <thaumcraft:ingot:1>,
		liquid: null,
		nugget: <thaumcraft:nugget:7>,
		plate: <thaumcraft:plate:3>,
		rod: null
	},
	zinc: {
		block: <techreborn:storage:8>,
		dust: <techreborn:dust:59>,
		gear: null,
		ingot: <techreborn:ingot:18>,
		liquid: null,
		nugget: <techreborn:nuggets:18>,
		plate: <techreborn:plates:33>,
		rod: null
	}
};


