
  global STAGES as string[string] = {

	zero : "zero",
	one : "one",
	two : "two",
	three : "three",
	four : "four",
	five : "five",
	six : "six",
	seven : "seven",
	eight : "eight",

	disabled : "disabled"
  };

  global itemStages as string[string] = {
	aluminium: "four",
	amber: "four",
	blackQuartz: "four",
	boron: "six",
	brass: "three",
	bronze: "two",
	chrome: "five",
	certus: "four",
	chargedCertus: "four",
	cinnabar: "four",
	compressedIron: "four",
	conductiveIron: "six",
	constantan: "four",
	copper: "one",
	darkSteel: "six",
	diamond: "four",
	ebonyPsiMetal: "six",
	electricalSteel: "six",
	electrum: "four",
	elementium: "four",
	emerald: "four",
	endSteel: "six",
	enderium: "six",
	energeticAlloy: "six",
	enhancedGalgadorian: "four",
	fluxedElectrum: "six",
	fluxCrystal: "six",
	galena: "four",
	galgadorian: "four",
	glowstone: "four",
	gold: "two",
	lapis: "four",
	invar: "four",
	iridium: "five",
	iron: "three",
	ironAlloy: "six", 
	ivoryPsiMetal: "six",
	lead: "two",
	lithium: "six",
	lumium: "six",
	magnesium: "six",
	manaInfused: "six",
	manaSteel: "four",
	nickel: "four",
	obsidian: "three",
	osmium: "seven",
	peridot: "five",
	platinum: "six",
	psiMetal: "six",
	pulsatingIron: "six",
	quartz: "four",
	redstone: "two",
	redstoneAlloy: "six",
	reinforcedMetal: "four",
	ruby: "four",
	rutile: "five",
	sapphire: "four",
	signalum: "six",
	silver: "two",
    soularium: "six",
	soulForgedSteel: "two",
	starMetal: "two",
	steel: "four",
	terraSteel: "four",
	tin: "two",
	titanium: "five",
	thaumium: "three",
	thorium: "six",
	tungsten: "five",
	tungstenSteel: "five",
	uranium: "six",
	vibrantAlloy: "six",
	voidMetal: "three",
	zinc: "five"
  };